app = "laboratoria-stream-server"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder:base"

[[services]]
  http_checks = []
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]
  
  [[services.ports]]
    port = 80
    handlers = ["http"]
    
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    grace_period = "1s"
    interval = "15s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"
    tls_skip_verify = false

[http_service]
  force_https = true
  internal_port = 8080
